### ISSUE TITLE
Node 8 - Failed at the ibm_db@2.2.1 install script / node-gyp related error

### ISSUE THREAD

**Issue by adriantanasa** [ibmdb/node-ibm_db#365]
The ibm_db module instalation is breaking Travis build on Github (dedicated) for Node 8.x given ibm_db install failure _npm ERR! Failed at the ibm_db@2.2.1 install script._ when using default settings.

## Root log error:

```
{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
```

```
gyp ERR! command "/home/travis/.nvm/versions/node/v8.9.4/bin/node" "/home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/travis/build/mySA/myMQClient/node_modules/ibm_db/installer/clidriver"

gyp ERR! cwd /home/travis/build/mySA/myMQClient/node_modules/ibm_db
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Solution

- using g++ 4.8 - sample yml file bellow 

```yml
language: node_js
node_js:
  - "8.9.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-4.8 
install:
  - npm install
script:
  - npm test
```
