### ISSUE TITLE
The database path "U" does not exist

### ISSUE THREAD

**Issue by kirrg001** [ibmdb/node-ibm_db#848]
I am using the docker image via docker-compose with the following configuration:

```
const connStr = 'HOSTNAME=localhost;UID=node;PWD=nodepw;PORT=58885;PROTOCOL=TCPIP';
ibmdb.createDbSync('test', connStr);
```

I am getting an error when I am trying to create a db:

```
creating database: mnjejowu HOSTNAME=localhost;UID=node;PWD=nodepw;PORT=58885;PROTOCOL=TCPIP
Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL1052N  The database path "U" does not exist.

    at Function.module.exports.createDbSync (node_modules/ibm_db/lib/odbc.js:211:24)
    at connect (tracing/database/db2/app.js:56:11)
    at Object.<anonymous> (tracing/database/db2/app.js:99:1)
```

docker-compose.yml:

```
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - 58885:50000
    environment:
      - PERSISTENT_HOME=true
      - BLU=false
      - HADR_ENABLED=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - SAMPLEDB=false
      - REPODB=false
      - IS_OSXFS=false
      - LICENSE=accept
      - DB2INSTANCE=node
      - DB2INST1_PASSWORD=nodepw
      - DB2_CREATE_DB_ON_PATH=true
    volumes: 
       - ./db2/database:/database
       - ./db2/db2_data:/db2_data
 ```

Docker log

```
db2_1              | FUNCTION: DB2 Common, OSSe, ossErrorIOAnalysis, probe:100
db2_1              | CALLED  : OS, -, realpath                         OSERR: EACCES (13)
db2_1              | DATA #1 : String, 100 bytes
db2_1              | A total of 2 analysis will be performed :
db2_1              |  - User info
db2_1              |  - Path access permission
db2_1              |
db2_1              |  Target file = /U
```

System: Monterey 12.2.1

Any idea what the reason for this error message is?

Thanks!
